### ISSUE TITLE
Not really an issue, more of suggestion

### ISSUE THREAD

**Issue by Medaleux** [Sniper1-1/Snipers_Moons#2]
Hi,
your moons seems pretty nice, but may I suggest to put all of them in an unified bundle ?
It'll be prety neat, especially in large modpacks (like mine tbh).
Sorry if it has already been asked or this isn't the correct place to ask.
Thx

**Comment by Sniper1-1** [comment]
One unified bundle was what I had done originally, but after some feedback and some consideration I think the current approach is actually better. Some people only want certain moons and one unified pack doesn’t really allow for that. It’s all or nothing. If I’d done one unified pack and also made the moons available for individual download if I update something I’ve got to do it in two places which is a bit of extra work. The way it’s set up now (the pack being primarily empty but with each moon as a standalone dependency) has the benefit of both allowing people to individually download specific moons or download all of them by downloading the pack (since mod managers automatically download the dependencies). I also only have to update in the one place, which is good for whenever I update stuff or if the game updates and breaks things, I can push the fixes for each moon as I fix them instead of having to wait to fix all of them before pushing the fixes.

So, unfortunately I think this current setup is better for more people and me as a dev. Yes, it does increase your mod count, but that’s really just visual annoyance which I think is worth the better file size/ram flexibility and dev flexibility.
